apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: h2-api-microservice
  title: "H2: API Microservice with Database"
  description: |
    Create a production-ready API microservice with PostgreSQL database,
    Redis caching, OpenAPI documentation, and full observability stack.
    Includes FastAPI/Express/Spring Boot, GitHub Actions CI/CD, and ArgoCD deployment.
  tags: [api, microservice, postgresql, redis, h2-enhancement, recommended]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:backend-engineering
  type: service
  parameters:
    - title: Application Information
      required: [name, owner, description]
      properties:
        name:
          title: Service Name
          type: string
          description: Unique name (lowercase, hyphens allowed)
          pattern: "^[a-z][a-z0-9-]*$"
          ui:autofocus: true
        description:
          title: Description
          type: string
        owner:
          title: Owner Team
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Technology Stack
      required: [language]
      properties:
        language:
          title: Language
          type: string
          enum: [python-fastapi, nodejs-express, java-spring, go-gin]
          enumNames: ["Python (FastAPI)", "Node.js (Express)", "Java (Spring Boot)", "Go (Gin)"]
          default: python-fastapi
        enableDatabase:
          title: Enable PostgreSQL
          type: boolean
          default: true
        enableRedis:
          title: Enable Redis
          type: boolean
          default: true

    - title: Environment & Deployment
      required: [environment]
      properties:
        environment:
          title: Target Environment
          type: string
          description: Which environment to deploy to
          enum: [dev, qa, prod]
          enumNames: ["Development", "QA / Staging", "Production"]
          default: dev
        azureSubscription:
          title: Azure Subscription ID
          type: string
          description: Required for infrastructure provisioning (leave empty for local)
        azureRegion:
          title: Azure Region
          type: string
          enum: [centralus, eastus]
          enumNames: ["Central US", "East US"]
          default: centralus
        enableArgoCD:
          title: Enable ArgoCD GitOps
          type: boolean
          default: true

    - title: Repository Settings
      required: [repoUrl]
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ['github.com']

  steps:
    - id: fetch-skeleton
      name: Fetch API Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          language: ${{ parameters.language }}
          enableDatabase: ${{ parameters.enableDatabase }}
          enableRedis: ${{ parameters.enableRedis }}
          environment: ${{ parameters.environment }}
          azureRegion: ${{ parameters.azureRegion }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
      - title: Open in Catalog
        entityRef: ${{ steps.register.output.entityRef }}
        icon: catalog
      - title: Open in Codespaces
        url: ${{ steps.publish.output.remoteUrl }}/codespaces/new
        icon: code
