apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: h2-reusable-workflows
  title: 'H2: Reusable GitHub Actions Workflows'
  description: 'Create a library of reusable GitHub Actions workflows for CI/CD,

    security scanning, and deployment automation.

    '
  tags:
  - github-actions
  - workflows
  - cicd
  - h2-enhancement
spec:
  owner: group:devops-engineering
  type: workflow-library
  parameters:
  - title: Workflow Library Configuration
    required:
    - name
    - owner
    properties:
      name:
        title: Library Name
        type: string
        pattern: ^[a-z][a-z0-9-]*$
      owner:
        title: Owner Team
        type: string
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind: Group
      includeWorkflows:
        title: Include Workflows
        type: array
        items:
          type: string
          enum:
          - build
          - test
          - security-scan
          - deploy
          - release
        uniqueItems: true
        default:
        - build
        - test
        - security-scan
        - deploy
        ui:widget: checkboxes
  - title: Environment & Deployment
    required:
    - environment
    properties:
      environment:
        title: Target Environment
        type: string
        description: Which environment to deploy to
        enum:
        - dev
        - qa
        - prod
        enumNames:
        - Development
        - QA / Staging
        - Production
        default: dev
      azureSubscription:
        title: Azure Subscription ID
        type: string
        description: Required for infrastructure provisioning (leave empty for local)
      azureRegion:
        title: Azure Region
        type: string
        enum:
        - centralus
        - eastus
        enumNames:
        - Central US
        - East US
        default: centralus
  - title: Repository Settings
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com
  steps:
  - id: fetch-skeleton
    name: Fetch Workflow Skeleton
    action: fetch:template
    input:
      url: ./skeleton
      values:
        name: ${{ parameters.name }}
        owner: ${{ parameters.owner }}
        includeWorkflows: ${{ parameters.includeWorkflows }}
  - id: publish
    name: Publish to GitHub
    action: publish:github
    input:
      description: Reusable workflows - ${{ parameters.name }}
      repoUrl: ${{ parameters.repoUrl }}
      defaultBranch: main
      repoVisibility: private
  - id: register
    name: Register in Catalog
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
      catalogInfoPath: /catalog-info.yaml
  output:
    links:
    - title: Repository
      url: ${{ steps.publish.output.remoteUrl }}
    - title: Catalog Entry
      entityRef: ${{ steps.register.output.entityRef }}
    - title: Open in Codespaces
      url: ${{ steps.publish.output.remoteUrl }}/codespaces/new
      icon: code
