apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: h1-documentation-site
  title: "H1: Documentation Site"
  description: |
    Create a documentation site using MkDocs with TechDocs integration.
    Includes automatic publishing to the developer portal.
  tags: [documentation, mkdocs, techdocs, h1-foundation]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: platform-team
  type: documentation
  parameters:
    - title: Documentation Site Configuration
      required: [name, owner]
      properties:
        name:
          title: Site Name
          type: string
          pattern: "^[a-z][a-z0-9-]*$"
        owner:
          title: Owner Team
          type: string
          ui:field: OwnerPicker
        description:
          title: Description
          type: string
          default: "Technical documentation site"
  steps:
    - id: fetch-skeleton
      name: Fetch Documentation Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "${{ parameters.description }}"
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.name }}
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Catalog Entry
        entityRef: ${{ steps.register.output.entityRef }}
